package mynamespace

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.

type NumberScalar int32

const (
	NumberScalarVariant1 NumberScalar = 4
	NumberScalarVariant2 NumberScalar = 2
)

func (f *NumberScalar) UnmarshalJSON(data []byte) error {
	var v int32
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*f = NumberScalar(v)
	return nil
}

func (f NumberScalar) MarshalJSON() ([]byte, error) {

	return json.Marshal(f)
}
