package mynamespace

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.

type StringNoScalar string

const (
	StringNoScalarVariant1 StringNoScalar = "Value1"
	StringNoScalarVariant2 StringNoScalar = "Value2"
)

func (f *StringNoScalar) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*f = StringNoScalar(v)
	return nil
}

func (f StringNoScalar) MarshalJSON() ([]byte, error) {

	return json.Marshal(f)
}
