package mynamespace

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.

type StringScalar string

const (
	StringScalarVariant1 StringScalar = "Value1"
	StringScalarVariant2 StringScalar = "Value2"
)

func (f *StringScalar) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*f = StringScalar(v)
	return nil
}

func (f StringScalar) MarshalJSON() ([]byte, error) {

	return json.Marshal(f)
}
