package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.

type Pet struct {
	Name string
	Age  int64
}

func (m *Pet) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["name"]; ok {
		if err := json.Unmarshal(v, &m.Name); err != nil {
			return err
		}
	}
	if v, ok := rawMsg["age"]; ok {
		if err := json.Unmarshal(v, &m.Age); err != nil {
			return err
		}
	}
	return nil
}

func (m Pet) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"name": m.Name,
		"age":  m.Age,
	}

	return json.Marshal(obj)
}
