package modeltest

import (
	"encoding/json"
	"time"
)

// This file is generated by the typespec compiler. Do not edit.
type Meeting struct {
	Duration time.Duration
}

func (m *Meeting) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["duration"]; ok {
		if err := json.Unmarshal(v, &m.Duration); err != nil {
			return err
		}
	}
	return nil
}

func (m Meeting) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"duration": m.Duration,
	}

	return json.Marshal(obj)
}
