package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.

type HasScalarNullable struct {
	ScalarNullableField Nullable[string]
}

func (m *HasScalarNullable) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["scalarNullableField"]; ok {
		if err := json.Unmarshal(v, &m.ScalarNullableField); err != nil {
			return err
		}
	}
	return nil
}

func (m HasScalarNullable) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"scalarNullableField": m.ScalarNullableField,
	}

	return json.Marshal(obj)
}
