package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.
type Cat struct {
	Name     string
	Nickname *string
}

func (m *Cat) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["name"]; ok {
		if err := json.Unmarshal(v, &m.Name); err != nil {
			return err
		}
	}
	if v, ok := rawMsg["nickname"]; ok {
		if err := json.Unmarshal(v, &m.Nickname); err != nil {
			return err
		}
	}
	return nil
}

func (m Cat) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"name": m.Name,
	}

	if m.Nickname != nil {
		obj["nickname"] = m.Nickname
	}

	return json.Marshal(obj)
}
