package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.
type Foo struct {
}

func (m Foo) Bar() Bar {
	return "one"
}

func (m *Foo) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	return nil
}

func (m Foo) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"bar": "one",
	}

	return json.Marshal(obj)
}

type Bar string

const (
	BarVariant2 Bar = "two"
)

func (f *Bar) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*f = Bar(v)
	return nil
}

func (f Bar) MarshalJSON() ([]byte, error) {
	return json.Marshal(f)
}
