package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.
type Dictionary struct {
	Words []string
}

func (m *Dictionary) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["words"]; ok {
		if err := json.Unmarshal(v, &m.Words); err != nil {
			return err
		}
	}
	return nil
}

func (m Dictionary) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"words": m.Words,
	}

	return json.Marshal(obj)
}
