package modeltest

import "encoding/json"

// This file is generated by the typespec compiler. Do not edit.
type Game struct {
	Name    string
	Players []Player
}

func (m *Game) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["name"]; ok {
		if err := json.Unmarshal(v, &m.Name); err != nil {
			return err
		}
	}
	if v, ok := rawMsg["players"]; ok {
		if err := json.Unmarshal(v, &m.Players); err != nil {
			return err
		}
	}
	return nil
}

func (m Game) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"name":    m.Name,
		"players": m.Players,
	}

	return json.Marshal(obj)
}

type Player struct {
	Name string
}

func (m *Player) UnmarshalJSON(data []byte) error {
	var rawMsg map[string]json.RawMessage
	if err := json.Unmarshal(data, &rawMsg); err != nil {
		return err
	}
	if v, ok := rawMsg["name"]; ok {
		if err := json.Unmarshal(v, &m.Name); err != nil {
			return err
		}
	}
	return nil
}

func (m Player) MarshalJSON() ([]byte, error) {
	obj := map[string]interface{}{
		"name": m.Name,
	}

	return json.Marshal(obj)
}
